# Introduction to R: Part Two

## Introductions and Overview

## What is RStudio

- RStudio is an *integrated development environment* (IDE) for the R programming language
- You can create, open, and edit scripts and other text file types
- You can create and manage project files
- You can build libraries, documents, and other projects
- View plots, tables, web apps, and more
- Help documentation explorer
- Package manager
- Debugger

## Opening RStudio

### Open in Windows

- start menu (see video below)
- desktop shortcut
- task bar shortcut

<video width="100%" autoplay muted loop controls>
  <source src="media/02-opening-rstudio-windows.webm" type="video/webm">
</video>

### Open in Linux

- application menu (see video below)
- dock shortcut

<video width="100%" autoplay muted loop controls>
  <source src="media/02-opening-rstudio-ubuntu.webm" type="video/webm">
</video>

## Navigating RStudio

- Four separate regions with individual *panes*
- Main panes are
  - source editor
  - console
  - environment and history
  - files, plots, packages, help, etc.

## Writing and running an Rscript

Writing a script allows one to re-use and re-write code. It means that you can also share your code, keep track of changes, and string together more complex commands to carry out an analysis.

1. Create a new file (`ctrl+shift+N`)
2. Type in an R command

You can run the entire script at once using the "source" button (`ctrl+shift+S` or `ctrl+shift+enter`), or you can run line-by-line (`ctrl+enter`).

## The -apply family of functions

`apply()`

`lapply()`

`sapply()`

`tapply()`

`vapply()`

## Control flow

### Conditionals

### Loops

### Switches

## Writing functions

## Working with libraries

## Creating a new project

## Best practices and style

## Conclusion
