---
title: "Workshop Learning Plan"
author: "Alex Knudson"
date: "4/6/2021"
output: 
  html_document:
    number_sections: true
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: true
    toc_depth: 2
    
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# R Workshop Series

- Details
  - Date, time, location
  - Presenters
- Lesson Plan
  - Necessary materials
  - Clear objectives
  - Background knowledge
  - Direct instruction
  - Student practice
  - Closure
  - Demonstration of learning (quick assessment)

## Introduction to R pt. 1

This workshop serves as a gentle introduction to programming with R, with a focus on application to data science and research. R basics will be covered, such as using the command line as a calculator, storing values in a variable, basic data structures (vector, matrix, list, data frame, etc.), and data types. We will show how to load basic data sets and access rows/columns, and summarize data with statistics and plots. We will also cover some considerations when choosing R over another language.

| Date         | Time        | Location | Presenter(s)          |
|:-------------|:------------|:---------|:----------------------|
| May 20, 2021 | 13:00-16:00 | DMSC 106 | Alex, Lucas, and Juli |

**Materials**

- Computer with `R` and `RStudio` installed
- Internet connection

**Objectives**

Students will be able to:

- open the R command line interface (CLI)
- access the built-in help docs
- perform basic arithmetic using R
- store data in variables
- list the environment variables
- understand the basic data types in R
- convert between the different data types
- understand and use the basic data structures in R
- access rows, columns, and elements of matrices and data frames
- read data from a `csv` into a data frame
- fit simple linear models
- summarize data and linear models
- create simple plots of 1-D and 2-D data
- understand the similarities and differences between R, Python, Julia, and other programming languages

**Background Knowledge**

Students should know:

- how to operate a computer
- arithmetic and order of operations
- basic statistics (summary statistics, simple linear models)
- basic ideas of plots and charts

**Direct Instruction**

| Activity                                                         | Duration   |
|:-----------------------------------------------------------------|:-----------|
| Introductions and overview                                       | 10 minutes |
| Opening the R command line                                       |  2 minutes |
| Accessing the built-in help docs                                 |  2 minutes |
| Doing basic arithmetic                                           |  5 minutes |
| Working with variables: storing, viewing, and removing variables |  4 minutes |
| Introduce different data types: types, storage, and class        | 10 minutes |
| Working with different data types: coercion and conversion       | 10 minutes |
| Overview of data structures in R                                 | 10 minutes |
| Working with data structures: vectors and matrices               | 10 minutes |
| Working with data structures: lists                              | 10 minutes |
| Working with data structures: data frames                        | 10 minutes |
| Reading data from a file                                         | 10 minutes |
| Fitting a linear model                                           | 15 minutes |
| Summarizing data frames and models                               | 10 minutes |
| Producing simple plots                                           | 10 minutes |
| Discussing R compared to other programming languages             | 15 minutes |

**Student Practice**

- TBD

**Closure**

- Recap the topics discussed
- Brief overview of the next session

**Assessment**

- TBD

## Introduction to R pt. 2

This workshop introduces scripting in R, including control flow, writing functions, and installing/loading libraries (and the differences between CRAN, GitHub, and Bioconductor packages). We will go over the `-apply` family of functions, simple graphs, and good practices in R (style guide, organization, etc.).

| Date         | Time        | Location | Presenter(s)          |
|:-------------|:------------|:---------|:----------------------|
| May 27, 2021 | 13:00-16:00 | DMSC 106 | Alex, Lucas, and Juli |

**Materials**

- Computer with `R` and `RStudio` installed
- Internet connection

**Objectives**

Students will be able to:

- open up RStudio and identify key parts of the IDE
- create, open, and save R scripts
- run R scripts line by line or all at once
- understand and use the `-apply` family of functions
- use control flow to execute complex tasks
- write functions and understand when to use them
- install and load libraries
- understand the differences between CRAN, Bioconductor, and GitHub
- understand what a style guide is and why it is important
- use good practices for writing and organizing code

**Background Knowledge**

Students should know:

- how to open an application on a computer
- the basic functions in R
- the basic ideas of conditional statements

**Direct Instruction**

| Activity                                               | Duration   |
|:-------------------------------------------------------|:-----------|
| Introductions and overview                             | 10 minutes |
| Getting acquainted with RStudio                        | 20 minutes |
| Writing and running an Rscript                         |  5 minutes |
| Using the `-apply` functions                           | 10 minutes |
| Using control flow - loops, switches, and conditionals | 20 minutes |
| Writing functions                                      | 15 minutes |
| Installing and loading libraries (NOTE: namespaces?)   | 20 minutes |
| Creating a new project in RStudio                      | 15 minutes |
| R Best practices and style                             | 30 minutes |


**Student Practice**

- TBD

**Closure**

- Recap the topics discussed
- Discuss how project organization, best practices, and style guide lead into reproducible data science

**Assessment**

- TBD

## Reproducible Data Science

We will discuss the problems we commonly see and introduce what it means to conduct reproducible data science. During the workshop, we will go through an example of setting up a new project folder, loading "messy" data, organizing scripts, and creating basic Rmarkdown reports. In reference to the messy data, we will go over what "tidy" data is, and how to use `tidyr` and other `tidyverse` libraries.

| Date         | Time        | Location           | Presenter(s)          |
|:-------------|:------------|:-------------------|:----------------------|
| June 3, 2021 | 13:00-16:00 | DMSC 106 + Virtual | Alex, Lucas, and Juli |

**Materials**

- Computer with `R` and `RStudio` installed
- Internet connection

**Objectives**

Students will be able to:

- understand the principles of reproducible [data] science
- identify bad project management habits
- organize a new project folder
- write code that is human-readable
- identify helpful libraries for data wrangling
- understand and implement the principles of immutable data
- create reports and other media using Rmarkdown
- use GitHub to track project changes

**Background Knowledge**

Students should know:

- scripting with R or a similar programming language
- how to create directories and folders
- basic git or a git GUI
- basic [markdown syntax](https://www.markdownguide.org/cheat-sheet/)

**Direct Instruction**

| Activity                                                  | Duration   |
|:----------------------------------------------------------|:-----------|
| Introductions                                             |  5 minutes |
| Code smells and project smells                            | 15 minutes |
| Overview of reproducible data science                     | 15 minutes |
| Project organization                                      | 20 minutes |
| Writing *human* readable code (NOTE: don't be too clever) | 15 minutes |
| Immutable data and data wrangling tools                   | 30 minutes |
| Creating dynamic reports and documents                    | 30 minutes |
| Tracking a project over time                              | 30 minutes |

**Student Practice**

- TBD

**Closure**

- Recap the topics discussed
- Share resources for topics discussed

**Assessment**

- TBD

## Tidy R

This will be a workshop fully devoted to data wrangling, including loading and cleaning "dirty" data, formatting "messy" data, and transforming "tidy" data to suit the task. There will be an emphasis on `tidyverse` libraries, but we will mention `data.table` as a faster alternative with fewer dependencies but with the trade-off of being less "readable".

| Date          | Time        | Location | Presenter(s)          |
|:--------------|:------------|:---------|:----------------------|
| June 10, 2021 | 13:00-16:00 | DMSC 106 | Alex, Lucas, and Juli |

**Materials**

- Computer with `R` and `RStudio` installed
- Internet connection

**Objectives**

Students will be able to:

- understand what "tidy" data is
- understand and use the various tidyverse packages
- read in data from various formats
- clean data using the tidyverse
- reshape wide data into long format, and long data into wide format

**Background Knowledge**

Students should know:

- how to program with R or some other scripting language
- how to navigate RStudio
- how to access the help documentation in R

**Direct Instruction**

| Activity                                   | Duration   |
|:-------------------------------------------|:-----------|
| Introductions and overview                 | 10 minutes |
| Introduction to tidy data                  | 10 minutes |
| Into the tidyverse                         | 30 minutes |
| Reading data from various formats          | 20 minutes |
| Data wrangling - cleaning                  | 30 minutes |
| Data wrangling - transforming and pivoting | 30 minutes |
| Alternative methods                        | 15 minutes |

**Student Practice**

- TBD

**Closure**

- Recap the topics discussed
- Share resources for topics discussed

**Assessment**

- TBD

## Producing Pretty Graphs and Tables with `base`, `ggplot2`, and `kable`

In this workshop, we will go over some principles of the visual display of quantitative data, and go in-depth with plotting in R with `base` and `ggplot2`. Additionally, since not all data is well represented in a graph, we will go over creating pretty tables using the `kable` and `kableExtra` packages.

| Date          | Time        | Location | Presenter(s)          |
|:--------------|:------------|:---------|:----------------------|
| June 17, 2021 | 13:00-16:00 | DMSC 106 | Alex, Lucas, and Juli |

**Materials**

**Objectives**

**Background Knowledge**

**Direct Instruction**

**Student Practice**

- TBD

**Closure**

**Assessment**

- TBD
